# This is a basic workflow that is manually triggered

name: Release
on:
  push:
    tags: [ "*" ]
  workflow_dispatch:
    inputs:
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Archive
        run: zip -qq -r Johnny-Utilities-${{ github.ref }}.alfredworkflow * -x .git
#        uses: montudor/action-zip@v0.1.1
#        with:
#          args: 
